#!/bin/sh
set -e

APP_NAME=remotecontrol-tray
LINK=/usr/local/bin/$APP_NAME
DESKTOP_DST="/usr/share/applications/$APP_NAME-$APP_NAME.desktop"

echo "Removing $APP_NAME from PATH"

if [ -L "$LINK" ]; then
    rm "$LINK"
fi

echo "Removing desktop entry"

if [ -f "$DESKTOP_DST" ]; then
    rm "$DESKTOP_DST"
fi

update-desktop-database /usr/share/applications || true

exit 0