name: Build Installers

on:
  push:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  # Job 1: Gather pom.xml version and create single Release
  create-release:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
      artifact: ${{ steps.artifact.outputs.artifact }}
    steps:
      - uses: actions/checkout@v6

      - name: Get project version
        id: version
        run: |
          echo "version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_OUTPUT

      - name: Get project artifactId
        id: artifact
        run: |
          echo "artifact=$(mvn help:evaluate -Dexpression=project.artifactId -q -DforceStdout)" >> $GITHUB_OUTPUT

      - name: Create or update GitHub release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: v${{ steps.version.outputs.version }}
          name: "${{ steps.artifact.outputs.artifact }} v${{ steps.version.outputs.version }}"
          body: "Release of Remote PC Control Tray version ${{ steps.version.outputs.version }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Job 2: Build installers for each OS
  build-installers:
    env:
      DIST_PATH: dist
      DIST_APP_PATH: dist/app
      INSTALLERS_PATH: installers
      INSTALLERS_APP_PATH: installers/app
      RELEASE_PATH: release
      PACKAGING_PATH: .packaging
      ICONS_PATH: .packaging/icons
    needs: create-release
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            installer: msi
            artifact: windows

          - os: ubuntu-latest
            installer: linux
            artifact: linux

          - os: macos-latest
            installer: dmg
            artifact: macos

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set up Java 21
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Build with Maven
        run: mvn -B clean package

      - name: Copy jar to distribution folder
        shell: bash
        run: |
          rm -rf "$DIST_PATH"
          mkdir -p "$DIST_APP_PATH"
          cp target/${{ needs.create-release.outputs.artifact }}.jar "$DIST_APP_PATH"/

      - name: Generate installer With jpackage
        shell: bash
        run: |
          set -e
          
          # Artifact name
          ARTIFACT=${{ needs.create-release.outputs.artifact }}
          
          # jar name
          JAR_NAME="$ARTIFACT.jar"
          
          # default version (from pom.xml)
          APP_VERSION="${{ needs.create-release.outputs.version }}"

          # Windows flags 
          WIN_FLAGS=()
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            WIN_FLAGS=(
              --win-menu
              --win-menu-group
              "$ARTIFACT"
              --win-shortcut
              --win-per-user-install
            )
          fi
          
          # Common flags for jpackage
          MAIN_FLAGS=(
            --name $ARTIFACT
            --input $DIST_APP_PATH
            --main-jar $JAR_NAME
            --dest $INSTALLERS_APP_PATH
            --app-version $APP_VERSION
            --copyright "Copyright © 2026 Enrique García (KGBis)"
            --vendor "Enrique García (KGBis)"
          )
          
          # for Windows and macOS
          NON_LINUX_FLAGS=(
            --about-url "https://github.com/KGBis/remotecontrol-tray"
            --license-file LICENSE
          )
          
          # icons
          ICON_FLAG=()
          
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
          ICON_FLAG+=("--icon" "$ICONS_PATH/computer.ico")
          
          elif [[ "${{ matrix.os }}" == "macos-latest" ]]; then
          ICON_FLAG+=("--icon" "$ICONS_PATH/computer.icns")
          
          elif [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
          ICON_FLAG+=("--icon" "$ICONS_PATH/computer.png")
          fi
          
          mkdir -p $INSTALLERS_PATH

          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            jpackage --type msi "${MAIN_FLAGS[@]}" "${NON_LINUX_FLAGS[@]}" "${ICON_FLAG[@]}" "${WIN_FLAGS[@]}"

          elif [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            jpackage --type dmg "${MAIN_FLAGS[@]}" "${NON_LINUX_FLAGS[@]}" "${ICON_FLAG[@]}"

          elif [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
            # install makeself
            sudo apt-get update
            sudo apt-get install -y makeself
          
            # execute jpackage
            jpackage --type app-image "${MAIN_FLAGS[@]}" "${ICON_FLAG[@]}"
          
            # copy install/uninstall scripts + .desktop
            cp -r "$PACKAGING_PATH/linux/"* "$INSTALLERS_PATH/"
          
            # ensure installer/uninstaller scripts executable
            chmod +x "$INSTALLERS_PATH/install.sh"
            chmod +x "$INSTALLERS_PATH/uninstall.sh"
          
            # create version file
            echo "$APP_VERSION" > "$INSTALLERS_PATH/VERSION"
          
            # create self installer
            makeself \
              --xz \
              --needroot \
              $INSTALLERS_PATH \
              "$ARTIFACT-$APP_VERSION-linux.run" \
              "Remote Control Tray installer" \
              ./install.sh
          fi

      - name: Normalize installer name
        shell: bash
        run: |
          # Artifact name
          ARTIFACT=${{ needs.create-release.outputs.artifact }}
          
          # default version (from pom.xml)
          APP_VERSION="${{ needs.create-release.outputs.version }}"
          
          # create release directory
          mkdir -p "$RELEASE_PATH"
          
          # move and rename installers to release
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            mv "$INSTALLERS_APP_PATH"/*.msi "$RELEASE_PATH/$ARTIFACT-$APP_VERSION-windows-x64.msi"
          elif [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            mv "$INSTALLERS_APP_PATH"/*.dmg "$RELEASE_PATH/$ARTIFACT-$APP_VERSION-macos.dmg"
          else 
            mv *.run "$RELEASE_PATH"/ || true # Linux 
          fi

      - name: Generate checksum
        shell: bash
        run: |
          # Artifact name
          ARTIFACT=${{ needs.create-release.outputs.artifact }}
          
          # default version (from pom.xml)
          APP_VERSION="${{ needs.create-release.outputs.version }}"
          
          cd "$RELEASE_PATH"
          ls -l
          
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            sha256sum *.msi > "$ARTIFACT-$APP_VERSION-windows-x64.sha256"
          elif [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            sha256sum *.dmg > "$ARTIFACT-$APP_VERSION-macos.sha256"
          else 
            sha256sum *.run > "$ARTIFACT-$APP_VERSION-linux.sha256" 
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: remotecontrol-tray-${{ matrix.artifact }}
          path: ${{ env.RELEASE_PATH }}/*

      - name: Upload assets to release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: v${{ needs.create-release.outputs.version }}
          files: ${{ env.RELEASE_PATH }}/*
          overwrite_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}